language: python
python:
  - "3.5"
script: python3 setup.py test
branches:
  only:
    - master
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "I2tSJslccvle9xJqBGJwDRPLmxSk/rkjYkpoMrG3IrC2R2BlEZLbpujP786MqOyGetV/t1OseHPcufPGRKGrdwCyzsjRV1mKbxwyf1aCjBowfpzFYb1ejNKgFn7tuWACHiJuINR4RRusEZDWBEZV+wlTWuzutr/HXa9kFYzXwlOvxMzsNosHOWL7FcpO3hGgcBWK5JREiuXe+QULenPsLYAel0PDBnLyf6bf3fhfuqVWynotFBvbxIyXLgSk61nrhs3AlVSeEo2Nt4dgGw/snjoNnA+VseroaoSfjhd5GgfhMTiXB47Lf5ORPCVRk+3Qr0a6Q1BlVAcZpVHrg7gzfqFThfh/ai+el0iFqw49WkneDy87AdaEP4yHIPKMDMMSpvBaMOOExwpKmam/uf/QgZ6NmzHCmxUIMcpqya/P8qMMDXrXwLkXbwk1TFmyeK3Gd9dIEbU/7neOMWmI7dfOqbjOz9d0DUEL3w1hnsMdMlO2n3fXIn3eheZvECclikcQ4QXJIIjhpSMtt180MBP7dSIAfM9IfYWWobgOYiLuSjcUZypJ0rvl/KqR88TDt6i18zOh6pbFWxW+nK9yz3Q1/OQfCDwfSdKUEoz4taqWB45Nfqx8A0Goo9rC/9BP0edJLcbhef00d5RJlGFji/UoduFl3BwBuhgwCKMYLajuk8k="
